#!/bin/bash
#PBS -q auto_free
#PBS -o /home/svu/e1498138/localgit/eGB-multi/run/logs/hmcnc_mcmc_e03.out
#PBS -e /home/svu/e1498138/localgit/eGB-multi/run/logs/hmcnc_mcmc_e03.err
#PBS -N hmcnc_mcmc_e03
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=4:mpiprocs=1:ompthreads=4:ngpus=1:mem=32gb

set -e

cd $PBS_O_WORKDIR;
mkdir -p /home/svu/e1498138/localgit/eGB-multi/run/logs

module load cuda12.4/toolkit/12.4.1
source /scratch/e1498138/anaconda3/bin/activate egb-multi

python /home/svu/e1498138/localgit/eGB-multi/run/hmcnc_mcmc_e03.py

echo "Job completed at $(date)"
